/** French copy only (storefront) */
export const fr = {
  brand: "Bébé Dépôt",
  byKhezami: "by Mme Khezami",
  navHome: "Accueil",
  navProducts: "Produits",
  navCategories: "Catégories",
  navDeposit: "Déposer",
  navStore: "Magasin",
  heroEyebrow: "Sélection 2026 · par Mme Khezami",
  heroTitle: "Pour les tout-petits, soigneusement sélectionné.",
  heroTitleHighlight: "tout-petits",
  heroSub:
    "Boutique bébé à Manouba : articles neufs et d'occasion vérifiés, choisis avec soin pour les familles tunisiennes.",
  collectionEveil: "Collection éveil",
  discoverShop: "Découvrir la boutique",
  depositProduct: "Déposer un produit",
  newBadge: "Nouveauté",
  trustVerified: "Produits vérifiés",
  trustVerifiedDesc: "Chaque article inspecté avant publication",
  trustDelivery: "Livraison Tunisie",
  trustDeliveryDesc: "Expédition rapide depuis Manouba",
  trustBaby: "Pensé pour bébé",
  trustBabyDesc: "Sélection douce, sûre et de qualité",
  categoriesEyebrow: "Catégories",
  exploreShop: "Explorer la boutique",
  ourBrands: "Nos marques",
  newsletterTitle: "Inscrivez-vous à notre newsletter",
  newsletterPlaceholder: "Votre adresse e-mail",
  newsletterSubmit: "S'inscrire",
  newsletterSuccess: "Merci ! Vous êtes inscrit(e) à notre newsletter.",
  newsletterError: "Impossible de finaliser l'inscription.",
  seeAll: "Tout voir",
  seeMore: "Voir plus",
  articles: "articles",
  article: "article",
  subCategory: "Sous-catégorie",
  depositBannerEyebrow: "Dépôt-vente",
  depositBannerTitle: "Vos produits méritent une seconde vie.",
  depositBannerDesc:
    "Confiez-nous vos articles bébé en bon état. Nous nous occupons de la sélection, la mise en valeur et la vente.",
  becomeDepositor: "Devenir déposant",
  step1Title: "Vous déposez l'article",
  step1Desc: "Apportez vos articles en boutique ou planifiez un retrait.",
  step2Title: "Nous vérifions et le mettons en vente",
  step2Desc: "Inspection, nettoyage, photos et mise en ligne soignée.",
  step3Title: "Vous êtes rémunéré dès la vente",
  step3Desc: "Reversement dès la vente, sans frais cachés.",
  selectionEyebrow: "Sélection",
  clientFeedbacksEyebrow: "Témoignages",
  clientFeedbacksTitle: "Avis des clients",
  favoritesTitle: "Les coups de cœur",
  shopEyebrow: "Boutique",
  allProducts: "Tous les produits",
  productsPageTitle: "Tous les produits",
  productsPageSub:
    "Parcourez notre catalogue complet : filtres par catégorie, marque, prix et disponibilité.",
  filterAll: "Tout",
  filterSearch: "Rechercher un produit…",
  filterCategory: "Catégorie",
  filterSubCategory: "Sous-catégorie",
  filterMark: "Marque",
  filterPrice: "Prix (TND)",
  filterMinPrice: "Min",
  filterMaxPrice: "Max",
  filterStock: "En stock uniquement",
  filterDepot: "Articles dépôt-vente",
  filterSort: "Trier par",
  sortNewest: "Plus récents",
  sortPriceAsc: "Prix croissant",
  sortPriceDesc: "Prix décroissant",
  sortNameAsc: "Nom A → Z",
  clearFilters: "Réinitialiser",
  activeFilters: "filtres actifs",
  showFilters: "Filtres",
  hideFilters: "Masquer",
  applyFilters: "Voir les résultats",
  resultsCount: "produits",
  loading: "Chargement…",
  noProducts: "Aucun produit pour le moment.",
  noImage: "Pas d'image",
  shopCategory: "BOUTIQUE",
  footerAbout:
    "Boutique bébé sélectionnée à la main par Mme Khezami. Produits vérifiés, disponibles en stock, commande et livraison soignées.",
  followUs: "Suivez-nous",
  rights: "Tous droits réservés",
  ourStore: "Notre magasin",
  storeCity: "Manouba, Tunisie",
  seeRoute: "Voir l'itinéraire",
  visitStore: "Visitez notre dépôt",
  locatedAt: "Situé à :",
  hoursTitle: "Horaires",
  closed: "Fermé",
  cart: "Panier",
  cartEmpty: "Votre panier est vide.",
  summary: "Résumé",
  products: "Produits",
  subtotal: "Sous-total",
  delivery: "Livraison",
  deliveryFree: "Offerte",
  total: "Total",
  checkout: "Passer la commande",
  payment: "Paiement",
  finalizeOrder: "Finaliser la commande",
  firstName: "Prénom",
  lastName: "Nom",
  phone: "Téléphone",
  email: "Email",
  address: "Adresse",
  confirmOrder: "Confirmer la commande",
  backToCart: "Retour au panier",
  addToCart: "Ajouter au panier",
  buyNow: "Acheter maintenant",
  inStock: "En stock",
  outOfStock: "Rupture de stock",
  alreadyInCart: "Déjà dans le panier",
  backToShopLink: "Retour à la boutique",
  verifiedBy: "Vérifié par Mme Khezami avant mise en vente",
  deliveryTime: "Livraison sous 24–48h en Tunisie",
  youMayLike: "Vous aimerez aussi",
  login: "Connexion",
  profile: "Mon profil",
  logout: "Se déconnecter",
  monday: "Lundi",
  tuesday: "Mardi",
  wednesday: "Mercredi",
  thursday: "Jeudi",
  friday: "Vendredi",
  saturday: "Samedi",
  sunday: "Dimanche",
} as const;

export const LOGO_SRC = "/depot.png";
export const WANTED_IMG = "/wanted.png";
export const WANTED_IMG_2 = "/wanted 2.png";
export const WANTED_IMG_3 = "/wanted 3.png";
export const WANTED_IMG_4 = "/wanted4.png";
export const WANTED_IMG_5 = "/wanted5.png";
